name: zip package and deploy to Octopus

on:
 workflow_dispatch:
 
jobs:
  lambda:
    name: octopus deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
   
      - name: Set Version
        run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Create artifacts folder
        run: |
          mkdir "$GITHUB_WORKSPACE/artifacts"
          mkdir "$GITHUB_WORKSPACE/artifacts/LambdaPackage"
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - name: Package the function
        run: |
          octo pack --id="TestLambdaFunction" --format="Zip" --version="$PACKAGE_VERSION" --basePath="modules/python" --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: Push the packages
        uses: OctopusDeploy/push-package-action@v1
        with:
          api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          server: ${{ secrets.OCTOPUSSERVERURL }}
          packages: "artifacts/TestLambdaFunction.${{ env.PACKAGE_VERSION }}.zip"
          space: ${{ secrets.OCTOPUSSERVER_SPACE }}
    
        
